name: Build OPA for Power

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
      latest_tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest.outputs.LATEST_TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build opa binary
        run: |
          git clone https://github.com/open-policy-agent/opa.git
          TAG=$(curl -s https://api.github.com/repos/open-policy-agent/opa/releases/latest | grep tag_name | cut -d '"' -f4)
          cd opa
          git checkout tags/$TAG
          env GOOS=linux GOARCH=ppc64le make ci-go-ci-build-linux-static
          TF_LATEST=$(curl -s https://api.github.com/repos/open-policy-agent/opa/releases/latest | grep tag_name | cut -d '"' -f4 | cut -c 2-)
          echo '::set-output name=LATEST_TAG::'$TF_LATEST
    
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: opa/_release/${{ inputs.latest_tag }}/opa_linux_ppc64le_static
          name: ${{ inputs.release }}
          replacesArtifacts: true
          draft: false
          prerelease: false
