name: Build OPA for Power

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build opa binary
        run: |
          git clone https://github.com/open-policy-agent/opa.git
          TAG=$(curl -shttps://api.github.com/repos/open-policy-agent/opa/releases/latest | grep tag_name | cut -d '"' -f4)
          git checkout tags/$TAG
          cd opa
          env GOOS=linux GOARCH=ppc64le make ci-go-ci-build-linux-static
          pwd
          ls -ltra
          cd _release
          ls -ltra
    
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: opa/_release/
          name: ${{ inputs.release }}
          replacesArtifacts: true
          draft: false
          prerelease: false
