name: Build OPA for Power

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: make sure repository is lowercase
        run: echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build opa binary
        run: |
          wget https://github.com/open-policy-agent/opa/archive/refs/tags/v0.46.1.zip
          unzip v0.46.1.zip
          cd opa-0.46.1
          env GOOS=linux GOARCH=ppc64le make ci-go-ci-build-linux-static
          pwd
          ls -ltra
          cd _release
          ls -ltra
    
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: 0.46.1
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: _release/0.46.1/opa_linux_ppc64le_static
          name: ${{ inputs.release }}
          replacesArtifacts: true
          draft: false
          prerelease: false
