name: Build OPA for Power

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build opa binary
        run: |
          wget https://github.com/open-policy-agent/opa/archive/refs/tags/v0.46.1.zip
          unzip v0.46.1.zip
          cd opa-0.46.1
          env GOOS=linux GOARCH=ppc64le make ci-go-ci-build-linux-static
          pwd
          ls -ltra
          cd _release
          ls -ltra
    
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: opa-0.46.1/_release/${{ inputs.release }}/opa_linux_ppc64le_static
          name: ${{ inputs.release }}
          replacesArtifacts: true
          draft: false
          prerelease: false
