name: Check for new opa ease

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-20.04
    
    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Get latest opa release
        id: latest
        run: |
          
          GE_LATEST=0.46.1
          echo '::set-output name=LATEST_RELEASE::'$GE_LATEST
          echo "Latest opa version "$GE_LATEST
          echo "Latest opa version: "$LATEST_RELEASE
  build-new-release:
    needs: [check-release]
    uses: ./.github/workflows/build_opa.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
